# Generated by Django 6.0.1 on 2026-02-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assets',
            field=models.ImageField(blank=True, null=True, upload_to='task_asset'),
        ),
    ]
