# Generated by Django 6.0.1 on 2026-02-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_event_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='participants',
            new_name='attendees',
        ),
    ]
