# Generated by Django 6.0.1 on 2026-02-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_rename_participants_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.event'),
        ),
    ]
