# Generated by Django 6.0.1 on 2026-02-08 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_event_attendees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='event',
        ),
        migrations.AddField(
            model_name='task',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='rsvp_task', to=settings.AUTH_USER_MODEL),
        ),
    ]
