# Generated by Django 6.0.1 on 2026-02-08 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_task_event_task_attendees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='rsvp_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='rsvp_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
